// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/movie_board_service/movie_board.proto

package movie_board_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoviesRequest) Reset() {
	*x = GetMoviesRequest{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesRequest) ProtoMessage() {}

func (x *GetMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetMoviesRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{0}
}

func (x *GetMoviesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMoviesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMovieByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieByIdRequest) Reset() {
	*x = GetMovieByIdRequest{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIdRequest) ProtoMessage() {}

func (x *GetMovieByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIdRequest.ProtoReflect.Descriptor instead.
func (*GetMovieByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{1}
}

func (x *GetMovieByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type InsertMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=Movie,proto3" json:"Movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertMovieRequest) Reset() {
	*x = InsertMovieRequest{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertMovieRequest) ProtoMessage() {}

func (x *InsertMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertMovieRequest.ProtoReflect.Descriptor instead.
func (*InsertMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{2}
}

func (x *InsertMovieRequest) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type UpdateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieRequest) Reset() {
	*x = UpdateMovieRequest{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieRequest) ProtoMessage() {}

func (x *UpdateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieRequest.ProtoReflect.Descriptor instead.
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMovieRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieRequest) Reset() {
	*x = DeleteMovieRequest{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRequest) ProtoMessage() {}

func (x *DeleteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRequest.ProtoReflect.Descriptor instead.
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMovieRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMovieByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Movie         *Movie                 `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieByIdResponse) Reset() {
	*x = GetMovieByIdResponse{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieByIdResponse) ProtoMessage() {}

func (x *GetMovieByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieByIdResponse.ProtoReflect.Descriptor instead.
func (*GetMovieByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{5}
}

func (x *GetMovieByIdResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMovieByIdResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type GetMoviesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Movies        []*GetMovieByIdResponse `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoviesResponse) Reset() {
	*x = GetMoviesResponse{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesResponse) ProtoMessage() {}

func (x *GetMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetMoviesResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{6}
}

func (x *GetMoviesResponse) GetMovies() []*GetMovieByIdResponse {
	if x != nil {
		return x.Movies
	}
	return nil
}

func (x *GetMoviesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type InsertMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertMovieResponse) Reset() {
	*x = InsertMovieResponse{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertMovieResponse) ProtoMessage() {}

func (x *InsertMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertMovieResponse.ProtoReflect.Descriptor instead.
func (*InsertMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{7}
}

func (x *InsertMovieResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Movie         *Movie                 `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieResponse) Reset() {
	*x = UpdateMovieResponse{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieResponse) ProtoMessage() {}

func (x *UpdateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieResponse.ProtoReflect.Descriptor instead.
func (*UpdateMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMovieResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type DeleteMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieResponse) Reset() {
	*x = DeleteMovieResponse{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieResponse) ProtoMessage() {}

func (x *DeleteMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieResponse.ProtoReflect.Descriptor instead.
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMovieResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Genre         string                 `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	Rating        float32                `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,5,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	Plot          string                 `protobuf:"bytes,6,opt,name=plot,proto3" json:"plot,omitempty"`
	RelaseDate    string                 `protobuf:"bytes,7,opt,name=relase_date,json=relaseDate,proto3" json:"relase_date,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	TicketPrice   float32                `protobuf:"fixed32,9,opt,name=ticket_price,json=ticketPrice,proto3" json:"ticket_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_board_service_movie_board_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_proto_movie_board_service_movie_board_proto_rawDescGZIP(), []int{10}
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Movie) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Movie) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Movie) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *Movie) GetPlot() string {
	if x != nil {
		return x.Plot
	}
	return ""
}

func (x *Movie) GetRelaseDate() string {
	if x != nil {
		return x.RelaseDate
	}
	return ""
}

func (x *Movie) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Movie) GetTicketPrice() float32 {
	if x != nil {
		return x.TicketPrice
	}
	return 0
}

var File_proto_movie_board_service_movie_board_proto protoreflect.FileDescriptor

const file_proto_movie_board_service_movie_board_proto_rawDesc = "" +
	"\n" +
	"+proto/movie_board_service/movie_board.proto\x12\vmovie_board\"<\n" +
	"\x10GetMoviesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"%\n" +
	"\x13GetMovieByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\">\n" +
	"\x12InsertMovieRequest\x12(\n" +
	"\x05Movie\x18\x01 \x01(\v2\x12.movie_board.MovieR\x05Movie\"$\n" +
	"\x12UpdateMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"$\n" +
	"\x12DeleteMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"P\n" +
	"\x14GetMovieByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12(\n" +
	"\x05movie\x18\x02 \x01(\v2\x12.movie_board.MovieR\x05movie\"d\n" +
	"\x11GetMoviesResponse\x129\n" +
	"\x06movies\x18\x01 \x03(\v2!.movie_board.GetMovieByIdResponseR\x06movies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"%\n" +
	"\x13InsertMovieResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"O\n" +
	"\x13UpdateMovieResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12(\n" +
	"\x05movie\x18\x02 \x01(\v2\x12.movie_board.MovieR\x05movie\"%\n" +
	"\x13DeleteMovieResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xee\x01\n" +
	"\x05Movie\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05genre\x18\x03 \x01(\tR\x05genre\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x02R\x06rating\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x05 \x01(\tR\tposterUrl\x12\x12\n" +
	"\x04plot\x18\x06 \x01(\tR\x04plot\x12\x1f\n" +
	"\vrelase_date\x18\a \x01(\tR\n" +
	"relaseDate\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12!\n" +
	"\fticket_price\x18\t \x01(\x02R\vticketPrice2\xaa\x03\n" +
	"\x11MovieBoardService\x12J\n" +
	"\tGetMovies\x12\x1d.movie_board.GetMoviesRequest\x1a\x1e.movie_board.GetMoviesResponse\x12S\n" +
	"\fGetMovieById\x12 .movie_board.GetMovieByIdRequest\x1a!.movie_board.GetMovieByIdResponse\x12P\n" +
	"\vInsertMovie\x12\x1f.movie_board.InsertMovieRequest\x1a .movie_board.InsertMovieResponse\x12P\n" +
	"\vUpdateMovie\x12\x1f.movie_board.UpdateMovieRequest\x1a .movie_board.UpdateMovieResponse\x12P\n" +
	"\vDeleteMovie\x12\x1f.movie_board.DeleteMovieRequest\x1a .movie_board.DeleteMovieResponseBAZ?github.com/Romma711/movie_theater/api/proto/movie_board_serviceb\x06proto3"

var (
	file_proto_movie_board_service_movie_board_proto_rawDescOnce sync.Once
	file_proto_movie_board_service_movie_board_proto_rawDescData []byte
)

func file_proto_movie_board_service_movie_board_proto_rawDescGZIP() []byte {
	file_proto_movie_board_service_movie_board_proto_rawDescOnce.Do(func() {
		file_proto_movie_board_service_movie_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_movie_board_service_movie_board_proto_rawDesc), len(file_proto_movie_board_service_movie_board_proto_rawDesc)))
	})
	return file_proto_movie_board_service_movie_board_proto_rawDescData
}

var file_proto_movie_board_service_movie_board_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_movie_board_service_movie_board_proto_goTypes = []any{
	(*GetMoviesRequest)(nil),     // 0: movie_board.GetMoviesRequest
	(*GetMovieByIdRequest)(nil),  // 1: movie_board.GetMovieByIdRequest
	(*InsertMovieRequest)(nil),   // 2: movie_board.InsertMovieRequest
	(*UpdateMovieRequest)(nil),   // 3: movie_board.UpdateMovieRequest
	(*DeleteMovieRequest)(nil),   // 4: movie_board.DeleteMovieRequest
	(*GetMovieByIdResponse)(nil), // 5: movie_board.GetMovieByIdResponse
	(*GetMoviesResponse)(nil),    // 6: movie_board.GetMoviesResponse
	(*InsertMovieResponse)(nil),  // 7: movie_board.InsertMovieResponse
	(*UpdateMovieResponse)(nil),  // 8: movie_board.UpdateMovieResponse
	(*DeleteMovieResponse)(nil),  // 9: movie_board.DeleteMovieResponse
	(*Movie)(nil),                // 10: movie_board.Movie
}
var file_proto_movie_board_service_movie_board_proto_depIdxs = []int32{
	10, // 0: movie_board.InsertMovieRequest.Movie:type_name -> movie_board.Movie
	10, // 1: movie_board.GetMovieByIdResponse.movie:type_name -> movie_board.Movie
	5,  // 2: movie_board.GetMoviesResponse.movies:type_name -> movie_board.GetMovieByIdResponse
	10, // 3: movie_board.UpdateMovieResponse.movie:type_name -> movie_board.Movie
	0,  // 4: movie_board.MovieBoardService.GetMovies:input_type -> movie_board.GetMoviesRequest
	1,  // 5: movie_board.MovieBoardService.GetMovieById:input_type -> movie_board.GetMovieByIdRequest
	2,  // 6: movie_board.MovieBoardService.InsertMovie:input_type -> movie_board.InsertMovieRequest
	3,  // 7: movie_board.MovieBoardService.UpdateMovie:input_type -> movie_board.UpdateMovieRequest
	4,  // 8: movie_board.MovieBoardService.DeleteMovie:input_type -> movie_board.DeleteMovieRequest
	6,  // 9: movie_board.MovieBoardService.GetMovies:output_type -> movie_board.GetMoviesResponse
	5,  // 10: movie_board.MovieBoardService.GetMovieById:output_type -> movie_board.GetMovieByIdResponse
	7,  // 11: movie_board.MovieBoardService.InsertMovie:output_type -> movie_board.InsertMovieResponse
	8,  // 12: movie_board.MovieBoardService.UpdateMovie:output_type -> movie_board.UpdateMovieResponse
	9,  // 13: movie_board.MovieBoardService.DeleteMovie:output_type -> movie_board.DeleteMovieResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_movie_board_service_movie_board_proto_init() }
func file_proto_movie_board_service_movie_board_proto_init() {
	if File_proto_movie_board_service_movie_board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_movie_board_service_movie_board_proto_rawDesc), len(file_proto_movie_board_service_movie_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_movie_board_service_movie_board_proto_goTypes,
		DependencyIndexes: file_proto_movie_board_service_movie_board_proto_depIdxs,
		MessageInfos:      file_proto_movie_board_service_movie_board_proto_msgTypes,
	}.Build()
	File_proto_movie_board_service_movie_board_proto = out.File
	file_proto_movie_board_service_movie_board_proto_goTypes = nil
	file_proto_movie_board_service_movie_board_proto_depIdxs = nil
}
